### ISSUE TITLE
No module named 'qgiscloud' 

### ISSUE THREAD

**Issue by pcav** [hdus/pg_raster_upload#1]
Upon install I get:

```
ModuleNotFoundError: No module named 'qgiscloud' 
Traceback (most recent call last):
  File "/usr/local/src/QGIS/build-qgis-3_16/output/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pg_raster_import/__init__.py", line 35, in classFactory
    from .pgraster_import import PGRasterImport
  File "/usr/local/src/QGIS/build-qgis-3_16/output/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pg_raster_import/pgraster_import.py", line 31, in 
    from .pgraster_import_dialog_base import PGRasterImportDialog
  File "/usr/local/src/QGIS/build-qgis-3_16/output/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pg_raster_import/pgraster_import_dialog_base.py", line 31, in 
    from .raster.raster_upload import RasterUpload
  File "/usr/local/src/QGIS/build-qgis-3_16/output/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pg_raster_import/raster/raster_upload.py", line 30, in 
    from qgiscloud.db_connections import DbConnections
  File "/usr/local/src/QGIS/build-qgis-3_16/output/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'qgiscloud'
```

**Comment by hdus** [comment]
Fixed in 1.0.3
