### ISSUE TITLE
Impossible to load the extension with 3.28.1-Firenze

### ISSUE THREAD

**Issue by image80** [hdus/pg_raster_upload#8]
Hello, Impossible to load the extension for me with 3.28.1-Firenze Firenze, fde3b8fbb8c (version installed from osgeo4w)

![image](https://user-images.githubusercontent.com/7910636/222109024-1d7807e9-e893-4da2-8fe0-47d8e8e7342f.png)

Impossible de charger l'extension 'raster2postgis' provoque une erreur lors de l'appel à sa méthode classFactory() 

ModuleNotFoundError: No module named 'unidecode' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~2.1/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/CELATI-L/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\raster2postgis\__init__.py", line 34, in classFactory
    from .raster2postgis import Raster2postgis
  File "C:\PROGRA~1/QGIS32~2.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/CELATI-L/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\raster2postgis\raster2postgis.py", line 30, in 
    from .raster_import_dialog import RasterImportDialog
  File "C:\PROGRA~1/QGIS32~2.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/CELATI-L/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\raster2postgis\raster_import_dialog.py", line 26, in 
    from unidecode import unidecode
  File "C:\PROGRA~1/QGIS32~2.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'unidecode'

Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.28.1-Firenze Firenze, fde3b8fbb8c 

Chemin Python :
C:/PROGRA~1/QGIS32~2.1/apps/qgis/./python
C:/Users/CELATI-L/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/CELATI-L/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~2.1/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.28.1\bin\python39.zip
C:\PROGRA~1\QGIS32~2.1\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~2.1\apps\Python39\lib
C:\Program Files\QGIS 3.28.1\bin
C:\PROGRA~1\QGIS32~2.1\apps\Python39
C:\PROGRA~1\QGIS32~2.1\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~2.1\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~2.1\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~2.1\apps\Python39\lib\site-packages\Pythonwin
C:/Users/CELATI-L/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by hdus** [comment]
The error message says:

``` ModuleNotFoundError: No module named 'unidecode'```

It looks like that `unidecode` is not installed on you computer. You can install it with 

```python3 -m pip install unidecode```
